version: '3.8'  # Adiciona a versão do Compose

services:
  mysql:
    image: mysql:8.0  # Especifica a versão 8.0 do MySQL
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
